// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/mcp4go/mcp4go/server/iface"
	"github.com/mcp4go/mcp4go/server/internal/handlers"
	"github.com/mcp4go/mcp4go/server/internal/router"
)

// Injectors from wire.go:

func initRouter(initializeHandler *handlers.InitializeHandler, setLevelHandler *handlers.SetLevelHandler, iResource iface.IResource, iPrompt iface.IPrompt, iTool iface.ITool, eventBus iface.EventBus) (router.IRouter, error) {
	initializedHandler := handlers.NewInitializedHandler()
	shutdownHandler := handlers.NewShutdownHandler()
	cancelHandler := handlers.NewCancelHandler()
	listPromptsHandler := handlers.NewListPromptsHandler(iPrompt)
	getPromptHandler := handlers.NewGetPromptHandler(iPrompt)
	listResourcesHandler := handlers.NewListResourcesHandler(iResource)
	readResourceHandler := handlers.NewReadResourceHandler(iResource)
	listResourceTemplatesHandler := handlers.NewListResourceTemplatesHandler(iResource)
	subscribeHandler := handlers.NewSubscribeHandler(iResource, eventBus)
	unsubscribeHandler := handlers.NewUnsubscribeHandler(iResource)
	listToolsHandler := handlers.NewListToolsHandler(iTool)
	callToolHandler := handlers.NewCallToolHandler(iTool)
	v := handlers.NewIHandlers(initializeHandler, initializedHandler, shutdownHandler, cancelHandler, setLevelHandler, listPromptsHandler, getPromptHandler, listResourcesHandler, readResourceHandler, listResourceTemplatesHandler, subscribeHandler, unsubscribeHandler, listToolsHandler, callToolHandler)
	routerRouter := router.NewRouter(v, eventBus)
	iRouter := router.NewIRouter(routerRouter)
	return iRouter, nil
}
